import Foundation

/// The AI-generated prompt engine: asks DeepSeek for a fresh journaling prompt
/// tailored to the chosen `JournalStyle`, and quietly falls back to the curated
/// `PromptBank` whenever the network, the API key, or the response isn't there.
///
/// This is the online counterpart to `PromptBank`. The bank keeps the app fully
/// functional and demoable offline; the engine upgrades a prompt to something
/// freshly written in the same voice when a key is configured. Callers never see
/// an error — every path returns a usable prompt, so the diary always has
/// something to write toward.
///
/// DeepSeek exposes an OpenAI-compatible Chat Completions API, so this talks raw
/// `URLSession` to `/chat/completions` with a `Bearer` key. The key is read from
/// the app's Info.plist (`DEEPSEEK_API_KEY`, wired through `project.yml` from the
/// build environment) or the process environment — never hardcoded, never
/// committed. No key ⇒ offline mode ⇒ `PromptBank`.
struct PromptEngine {
    static let shared = PromptEngine()

    private let apiKey: String?
    private let session: URLSession
    private let model = "deepseek-chat"
    private let endpoint = URL(string: "https://api.deepseek.com/chat/completions")!

    init(apiKey: String? = PromptEngine.resolveAPIKey(), session: URLSession = .shared) {
        self.apiKey = apiKey
        self.session = session
    }

    /// Whether an API key is configured. When false, `prompt(for:excluding:)`
    /// always returns a `PromptBank` entry without touching the network — the UI
    /// can skip loading affordances entirely.
    var isOnline: Bool { apiKey?.isEmpty == false }

    /// A journaling prompt for `style`, freshly generated by DeepSeek when online
    /// and drawn from `PromptBank` otherwise. `excluding` avoids repeating the
    /// prompt currently on screen (matters most for the shuffle control and the
    /// offline pool). Never throws — failures fall back to the bank.
    func prompt(for style: JournalStyle, excluding current: String? = nil) async -> String {
        guard let apiKey, !apiKey.isEmpty else {
            return PromptBank.random(for: style, excluding: current)
        }
        do {
            return try await generate(for: style, excluding: current, apiKey: apiKey)
        } catch {
            return PromptBank.random(for: style, excluding: current)
        }
    }

    // MARK: - DeepSeek Chat Completions API

    private func generate(for style: JournalStyle, excluding current: String?, apiKey: String) async throws -> String {
        var request = URLRequest(url: endpoint)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
        request.timeoutInterval = 20

        let body = ChatRequest(
            model: model,
            maxTokens: 256,
            messages: [
                .init(role: "system", content: systemPrompt(for: style)),
                .init(role: "user", content: userPrompt(for: style, excluding: current)),
            ]
        )
        request.httpBody = try JSONEncoder().encode(body)

        let (data, response) = try await session.data(for: request)
        guard let http = response as? HTTPURLResponse, (200..<300).contains(http.statusCode) else {
            throw PromptEngineError.badResponse
        }

        let decoded = try JSONDecoder().decode(ChatResponse.self, from: data)
        let text = decoded.choices
            .first?
            .message
            .content?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .trimmingCharacters(in: CharacterSet(charactersIn: "\""))

        guard let text, !text.isEmpty else { throw PromptEngineError.empty }
        return text
    }

    /// A style-specific voice guide. The framing mirrors `JournalStyle.subtitle`
    /// and the tone of `PromptBank` so generated prompts read like the app's own.
    private func systemPrompt(for style: JournalStyle) -> String {
        """
        You write a single journaling prompt for a warm, handwritten diary app.
        The chosen style is "\(style.title)": \(style.subtitle)

        Write one fresh prompt in that style — evocative, specific, and gentle, \
        one or two sentences, second person, inviting reflection rather than \
        demanding it. Match the voice of these examples in tone and length:
        \(PromptBank.prompts(for: style).prefix(4).map { "- \($0)" }.joined(separator: "\n"))

        Respond with only the prompt itself. No preamble, no quotation marks, \
        no trailing commentary.
        """
    }

    private func userPrompt(for style: JournalStyle, excluding current: String?) -> String {
        if let current, !current.isEmpty {
            return "Write a new \(style.title) prompt. Do not repeat this one: \"\(current)\""
        }
        return "Write a \(style.title) prompt."
    }

    // MARK: - API-key resolution

    /// Reads `DEEPSEEK_API_KEY` from the process environment first (handy for a
    /// scheme env var in the simulator), then the Info.plist value wired through
    /// `project.yml`. Returns nil when neither is set, which selects offline mode.
    static func resolveAPIKey() -> String? {
        if let env = ProcessInfo.processInfo.environment["DEEPSEEK_API_KEY"],
           !env.isEmpty {
            return env
        }
        if let plist = Bundle.main.object(forInfoDictionaryKey: "DEEPSEEK_API_KEY") as? String,
           !plist.isEmpty,
           // A build with the setting unset can bake in the literal placeholder.
           plist != "$(DEEPSEEK_API_KEY)" {
            return plist
        }
        return nil
    }
}

private enum PromptEngineError: Error {
    case badResponse
    case empty
}

// MARK: - Wire types (DeepSeek / OpenAI-compatible Chat Completions)

private struct ChatRequest: Encodable {
    let model: String
    let maxTokens: Int
    let messages: [Message]

    enum CodingKeys: String, CodingKey {
        case model, messages
        case maxTokens = "max_tokens"
    }

    struct Message: Encodable {
        let role: String
        let content: String
    }
}

private struct ChatResponse: Decodable {
    let choices: [Choice]

    struct Choice: Decodable {
        let message: Message
    }

    struct Message: Decodable {
        let content: String?
    }
}
